### ISSUE TITLE
Add advanced short syntax todo.txt style

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#487]
Add support for a todo.txt style short syntax while maintaining support for estimates.

https://github.com/todotxt/todo.txt

- [ ]  ~~due:sugarjs  advanced date stuff viasugarjs~~ 
- [x] timespent/estimate via 2h/3h
- [x] projects via +projectName
- [x] tags via #tagTitle

- [ ] ~~x1-1-21 => 1-1-21 9:00~~
- [ ] ~~x1-1-21 11:00 => 1-1-21 11:00~~
- [ ] ~~(momentParsableString) => moment date parsing~~
- [ ] ~~x11:00 =>  (today or tomorrow, depending on time)11:00~~
- [x] also fix new tags not being added to tag list

Example
"Do something @home +private project 1h/2h due:2-2-22"

**Comment by smalltimer** [comment]
Whoa! That looks like a great set of features. I think it will also draw in users who use todo.txt to maintain their lists. 

Btw, in #372 when I added tags with a # they weren't added to the list of tags in the left menu. That said I haven't tried the latest build yet.

**Comment by johannesjo** [comment]
The issue in 372 is not fixed yet... Thanks for the reminder! Haven't found the time to do it, but I try to fix it when this feature here comes to life.

**Comment by smalltimer** [comment]
Ah gotcha. Thanks for explaining.

**Comment by johannesjo** [comment]
I made some good progress on the feature. Some help testing it would be very much appreciated. It currently resides on this branch:
https://github.com/johannesjo/super-productivity/tree/feat/advanced-short-syntax

I tried to skip the due stuff for now as it is tricky to implement and sugarjs doesn't really work as I envisioned it. Maybe it is something we can extend later on, as I don't want to drag on developing this forever :).

**Comment by johannesjo** [comment]
I'll also publish the changes here, so you don't have to build the app yourself:
https://test-app.super-productivity.com/#/tag/TODAY/tasks

Take care though as this instance is syncing with the same dropbox instance if activated.

**Comment by smalltimer** [comment]
Thanks! That was so quick. I should be able to test it out some time next week and give some feedback. The due: is the least intuitive part of the todo.txt syntax, and I think your app already has very decent UI to schedule tasks. So for me it makes sense to postpone implementing the due: parsing till you have some more time on your hands.

**Comment by smalltimer** [comment]
Hi @johannesjo I've been testing it out today morning in the browser and it seems to be working nicely! I was also thinking of these two things within the task-input field:

1. While you are writing down the task, it would be good to highlight the recognised tags or project name. E.g., if the user is typing "Task 1 +P2 #T1", right after the program recognises that the user has typed in a project name or a tag, it could be highlighted or given a different background. You already implement such backgrounds in the Edit Tags box where each tag has a background (I can attach a screenshot if you'd like). 
2. When the user types in a + or a #, show the user a list of pre-existing projects/tags which can be chosen from using the up/down arrows and (say) the tab key. 

The features you set out to implement already work, so these are just enhancements. I don't think they are necessary for a first version of the software with these features. Thank you for putting in your time and your effort in this project. 

Btw, I recently noticed that you have also made .debs available. I have moved from the snap to the .deb packages and they are much faster for some reason. It is really awesome that you make them available - thanks for that! :+1:

**Comment by johannesjo** [comment]
@smalltimer thank you very much for the feedback.  

I'd also like to see these 2 improvements very much, but as you say I think it's something for later on as it is not trivial to implement. I have opened up another issue for that:
https://github.com/johannesjo/super-productivity/issues/500
(btw. congrats on the 500th issue ;))

**Comment by smalltimer** [comment]
Brilliant! Had no idea that these features were so tricky to implement (can you tell I'm not a programmer? :smile:). If you make a pre-release available in .deb I can test that as well. Not sure when though as next week is crazy full for me, but hopefully by next weekend for sure.
